### ISSUE TITLE
How do I press ESCAPE to close the modal?

### ISSUE THREAD

**Issue by andynhoo** [MessiJS/MessiJS#67] opened 2015-02-08 15:53 UTC
How do I press ESCAPE to close the modal?
Would to close the modal call a function?

**Comment by kgust** [comment] 2015-02-20 21:47
MessiJS currently does not support that feature. I've added this a feature request.

To answer your question—because this is not a supported feature—you would need to open the dialog, add a listener for either `onkeyup` or `onkeypress` and close the dialog if "ESC" is detected.

**Comment by kgust** [comment] 2017-01-16 04:55
I'm closing this a duplicate of #18.

**Closed by kgust** 2017-01-16 04:55 UTC
Labels: feature, question
